import ProjectDescription

let workspace = Workspace(
    name: "KuringWorkSpace",
    projects: [
        "Projects/App",
        "Projects/KuringLink",
        "Projects/DesignSystem",
        "Projects/Core"
    ],
    schemes: [
        Scheme(
            name: "Prod-Kuring",
            buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Prod-Kuring")]),
            runAction: .runAction(configuration: .release),
            archiveAction: .archiveAction(configuration: .release),
            profileAction: .profileAction(configuration: .release),
            analyzeAction: .analyzeAction(configuration: .release)
        ),
        Scheme(
            name: "Dev-Kuring",
            buildAction: .buildAction(targets: [.project(path: "Projects/App", target: "Dev-Kuring")]),
            runAction: .runAction(configuration: .debug),
            archiveAction: .archiveAction(configuration: .debug),
            profileAction: .profileAction(configuration: .debug),
            analyzeAction: .analyzeAction(configuration: .debug)
        ),
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
