name: 쿠링 스위프트 패키지 빌드하기

on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/쿠링') && contains(github.event.comment.body, '패키지 빌드')
    runs-on: macos-13  #최신버전
    steps:
      # 빌드 요청 시작
      - name: Build iOS17
        run: |
          echo "start build"
         
      # build package 빌드 응답 커멘트
      - name: Add Build comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔨 iOS 17.0.1 iPhone 15 Pro 에서 스위프트 패키지를 빌드합니다.'
            })

      # 코드를 체크아웃 합니다.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
    
      # Xcode 버전을 설정합니다.
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      # package-kuring 패키지를 빌드합니다. (최소 버전)
      - name: package-kuring 의 App 스킴 빌드
        run: |
          cd package-kuring
          xcodebuild build -scheme App -destination 'platform=iOS Simulator,OS=latest,name=iPhone 14 Pro' -skipMacroValidation
      
      # 빌드 성공시 커멘트
      - name: Add Build comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ 패키지를 성공적으로 빌드했습니다.'
            })
            
      # 빌드 실패시 커멘트
      - name: Notify failure
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📬 패키지 빌드에 실패했습니다. Actions에서 실패 결과를 확인해주세요.'
            })
        if: failure()
